### ISSUE TITLE
Error when build with NextJs  - flagsmith-es 3.9.0 - Type error: 'global' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

### ISSUE THREAD

**Issue by 001123** [Flagsmith/flagsmith-js-client#139]
After upgrade from `"flagsmith-es": "3.8.1",` to `"flagsmith-es": "3.9.0",` I got error when run build.

```js
Type error: 'global' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

  1 | import {IFlagsmith, IInitConfig} from "./types";
> 2 | var global = typeof global != "undefined" ? global: typeof window != 'undefined' ? window : {}
    |     ^
  3 | let _fetch: typeof global.fetch;
  4 | let AsyncStorage;
  5 | const FLAGSMITH_KEY = "BULLET_TRAIN_DB";

> Build error occurred
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (D:\git\saladin-app\node_modules\next\dist\compiled\jest-worker\index.js:1:11661)
    at ChildProcessWorker._onExit (D:\git\saladin-app\node_modules\next\dist\compiled\jest-worker\index.js:1:12599)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  type: 'WorkerError'
}
```

Dev info: 
"next": "12.2.5"
node: v16.16.0

**Comment by kyle-ssg** [comment]
This should be resolved in @3.9.1, thank you for reporting
